# Test-level dependencies: the older the better. Inhibit dependabot, so we only accept manual updates.
version: 2
updates:
  # Disable Dependabot for ci/docker (all ecosystems)
  - package-ecosystem: "docker"
    directory: "/ci/docker"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "pip"
    directory: "/ci/docker"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/ci/docker"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "github-actions"
    directory: "/ci/docker"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  # Disable Dependabot for tests/integration (all ecosystems)
  - package-ecosystem: "docker"
    directory: "/tests/integration"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "pip"
    directory: "/tests/integration"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/tests/integration"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "github-actions"
    directory: "/tests/integration"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  # Disable Dependabot for docker/test (all ecosystems)
  - package-ecosystem: "docker"
    directory: "/docker/test"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "pip"
    directory: "/docker/test"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "npm"
    directory: "/docker/test"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"

  - package-ecosystem: "github-actions"
    directory: "/docker/test"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "*"
