[package]
name = "_ch_rust_blake3"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.2.0"
libc = "0.2.132"

[lib]
crate-type = ["staticlib"]

[profile.release]
debug = true

[profile.release-thinlto]
inherits = "release"
# BLAKE3 module requires "full" LTO (not "thin") to get additional 10% performance benefit
lto = true
