[package]
edition = "2021"
name = "_ch_rust_prql"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prql-compiler = "0.9.3"
serde_json = "1.0"

[lib]
crate-type = ["staticlib"]

[profile.release]
debug = true

[profile.release-thinlto]
inherits = "release"
lto = true
