name: GitHub Actions Hello self hosted
description: Trying GithubActions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted]
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by me!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: docker run hello-world
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: Style Check
        env:
          YANDEX_S3_ACCESS_KEY_ID: ${{ secrets.YANDEX_S3_ACCESS_KEY_ID }}
          YANDEX_S3_ACCESS_SECRET_KEY: ${{ secrets.YANDEX_S3_ACCESS_SECRET_KEY }}
        run: cd $GITHUB_WORKSPACE/tests/ci && python3 style_check.py
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          ls $RUNNER_TEMP
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: ${{ runner.temp }}/report.html
      - run: ls -la $RUNNER_TEMP
      - run: echo "üçè This job's status is ${{ job.status }}."
