name: TagsStableWorkflow
# - Gets artifacts from S3
# - Sends it to JFROG Artifactory
# - Adds them to the release assets

env:
  # Force the stdout and stderr streams to be unbuffered
  PYTHONUNBUFFERED: 1

on: # yamllint disable-line rule:truthy
  push:
    tags:
    - 'v*-prestable'
    - 'v*-stable'
    - 'v*-lts'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Test tag'
        required: true 
        type: string


jobs:
  UpdateVersions:
    runs-on: [self-hosted, style-checker]
    steps:
    - name: Set test tag
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "GITHUB_TAG=${{ inputs.tag }}" >> "$GITHUB_ENV"
    - name: Get tag name
      if: github.event_name != 'workflow_dispatch'
      run: |
        echo "GITHUB_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
    - name: Generate versions
      env:
        GITHUB_TOKEN: ${{ secrets.ROBOT_CLICKHOUSE_COMMIT_TOKEN }}
      run: |
        ./utils/list-versions/list-versions.sh > ./utils/list-versions/version_date.tsv
        GID=$(id -g "${UID}")
        docker run -u "${UID}:${GID}" -e PYTHONUNBUFFERED=1 \
            --volume="${GITHUB_WORKSPACE}:/ClickHouse" clickhouse/style-test \
                /ClickHouse/utils/changelog/changelog.py -vv --gh-user-or-token="$GITHUB_TOKEN" \
                --output="/ClickHouse/docs/changelogs/${GITHUB_TAG}.md" --jobs=5 "${GITHUB_TAG}"
        git add "./docs/changelogs/${GITHUB_TAG}.md"
        git diff HEAD
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      env:
        GITHUB_TOKEN: ${{ secrets.ROBOT_CLICKHOUSE_COMMIT_TOKEN }}
      with:
        author: "robot-clickhouse <robot-clickhouse@users.noreply.github.com>"
        committer: "robot-clickhouse <robot-clickhouse@users.noreply.github.com>"
        commit-message: Update version_date.tsv and changelogs after ${{ env.GITHUB_TAG }}
        branch: auto/${{ env.GITHUB_TAG }}
        delete-branch: true
        title: Update version_date.tsv and changelogs after ${{ env.GITHUB_TAG }}
        labels: do not test
        body: |
          Update version_date.tsv and changelogs after ${{ env.GITHUB_TAG }}

          ### Changelog category (leave one):
          - Not for changelog (changelog entry is not required)
